# Site settings
author: Troy Christy
title: Troy's Livejournal
header-img: img/home-bg.png
email: troy.christy@icloud.com
copyright_name: Troy Christy
description: > # this means to ignore newlines until "baseurl:"
  Wheres the glittery gifs? 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TroyC9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
